Repository WildMeOrg/Wildbook, pull requests merged in 2024-08, with the labels that each got.

#654 Neutral config
  devops/deploy/.dockerfiles/tomcat/commonConfiguration.properties
  devops/development/.dockerfiles/tomcat/commonConfiguration.properties
  src/main/resources/bundles/commonConfiguration.properties
  src/main/resources/bundles/en/index.properties
  src/main/webapp/citing.jsp
  src/main/webapp/userAgreement.jsp
Labels: bug, techdebt

#655 master to seals
  devops/deploy/.dockerfiles/tomcat/commonConfiguration.properties
  devops/development/.dockerfiles/tomcat/commonConfiguration.properties
  src/main/resources/bundles/commonConfiguration.properties
  src/main/resources/bundles/en/index.properties
  src/main/webapp/citing.jsp
  src/main/webapp/userAgreement.jsp
Labels: project_support

#661 Fix subsepcies search support
  src/main/webapp/encounters/encounterSearch.jsp
  src/main/webapp/individualSearch.jsp
  src/main/webapp/occurrenceSearch.jsp
Labels: bug

#665 point to new docs site and donate
  README.md
  frontend/src/constants/footerMenu.js
  frontend/src/constants/navMenu.js
  src/main/resources/bundles/de/encounter.properties
  src/main/resources/bundles/de/individuals.properties
  src/main/resources/bundles/de/occurrence.properties
  src/main/resources/bundles/en/encounter.properties
  src/main/resources/bundles/en/individuals.properties
  src/main/resources/bundles/en/occurrence.properties
  src/main/resources/bundles/es/encounter.properties
  src/main/resources/bundles/es/individuals.properties
  src/main/resources/bundles/es/occurrence.properties
  src/main/resources/bundles/fr/encounter.properties
  src/main/resources/bundles/fr/individuals.properties
  src/main/resources/bundles/fr/occurrence.properties
  src/main/resources/bundles/it/encounter.properties
  src/main/resources/bundles/it/individuals.properties
  src/main/resources/bundles/it/occurrence.properties
  src/main/resources/servletResponseTemplate.htm
  src/main/webapp/footer.jsp
Labels: project_support

#674 Update submit.properties
  src/main/resources/bundles/en/submit.properties
Labels: enhancement

#679 de-ocean'd the overview
  src/main/webapp/overview.jsp
Labels: enhancement, techdebt, project_support

#681 cleanup of header and images
  src/main/resources/bundles/de/index.properties
  src/main/resources/bundles/en/index.properties
  src/main/resources/bundles/es/index.properties
  src/main/resources/bundles/fr/index.properties
  src/main/resources/bundles/it/index.properties
  src/main/webapp/images/action.jpg
Labels: techdebt, project_support

#680 update WB Version number for next release
  pom.xml
Labels: project_support

#687 bump logback version
  pom.xml
Labels: dependencies, java

#688 version change for rabbitmq lib
  pom.xml
Labels: dependencies, java

#689 (way) upgrade org.json java library
  pom.xml
Labels: dependencies, java

#703 missing german from react update
  frontend/public/flags/de.png
  frontend/src/App.jsx
  frontend/src/constants/locales.js
  frontend/src/locale/de.json
Labels: techdebt, project_support
